# Generated by Django 3.1.4 on 2020-12-01 16:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('agent', models.CharField(max_length=100, verbose_name='Контрагент')),
                ('comment', models.CharField(max_length=150, verbose_name='Текст заказа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма заказа')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
